package com.test.kt.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Book")
public class Book {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String bookId;

    @DynamoDBAttribute
    private  String bookRef;
}